Repository main-10-2team/boardgame-frontend, pull requests merged in 2025-08, with the labels that each got.

#48 feat: 보드게임 찾기 페이지 및 컴포넌트 구현(#27)
  next.config.ts
  src/app/games/page.tsx
  src/app/globals.css
  src/assets/mocks/gameListData.ts
  src/components/common/Dropdown.tsx
  src/components/common/StarRating.tsx
  src/components/game/FilterSidebar.tsx
  src/components/game/GameItem.tsx
  src/components/game/GameList.tsx
  src/components/game/LikeButton.tsx
  src/components/layout/Breadcrumbs.tsx
  src/components/layout/Grid.tsx
  src/constants/category/breadcrumbs.ts
  src/hooks/useOutsideClick.ts
  src/types/game/game.ts
  src/utils/formatDifficulty.ts
Labels: ✨feature

#51 feat: Not Found 페이지 추가 (#24)
  src/app/not-found.tsx
  src/components/common/Button.tsx
  src/constants/button/button.ts
  src/constants/category/menuItems.tsx
Labels: ✨feature

#52 feat: 마이페이지 내 정보/수정 페이지 UI 구현
  src/app/mypage/page.tsx
  src/app/mypage/profile/edit/page.tsx
  src/app/mypage/profile/page.tsx
  src/assets/mocks/userProfile.ts
  src/components/common/Input.tsx
  src/components/layout/Footer.tsx
  src/components/myPage/SideMenu.tsx
  src/components/myPage/modals/PasswordChangeModal.tsx
  src/components/myPage/modals/PhoneChangeModal.tsx
  src/components/myPage/modals/WithdrawalModal.tsx
  src/components/myPage/profile/ProfileDetail.tsx
  src/components/myPage/profile/ProfileInfoSection.tsx
  src/components/myPage/profile/WithdrawalButton.tsx
  src/types/user/user.ts
Labels: ✨feature

#61 feat: 마이페이지 좋아요 목록 UI 구현 (#35)
  src/app/mypage/likes/page.tsx
  src/app/mypage/profile/edit/page.tsx
  src/app/mypage/profile/page.tsx
  src/assets/mocks/likeList.ts
  src/components/common/modal/ConfirmModal.tsx
  src/components/myPage/like/LikeItemCard.tsx
  src/components/myPage/like/LikeList.tsx
  src/components/myPage/modals/PasswordChangeModal.tsx
  src/components/myPage/modals/PhoneChangeModal.tsx
  src/components/myPage/modals/WithdrawalModal.tsx
  src/types/user/like.ts
Labels: ✨feature

#63 refactor: GameItem 컴포넌트 수정(#62)
  src/components/game/GameItem.tsx
  src/components/game/GameList.tsx
  src/components/game/LikeButton.tsx
Labels: ♻️ refactor

#21 feat: toast 컴포넌트 시스템 구현 (#17)
  src/app/globals.css
  src/components/common/Toast.tsx
  src/constants/toast/toast.ts
  src/hooks/useToast.ts
Labels: ✨feature

#64 feat: 마이페이지 내 리뷰 UI 구현 (#33)
  src/app/my-page/likes/page.tsx
  src/app/my-page/page.tsx
  src/app/my-page/profile/edit/page.tsx
  src/app/my-page/profile/page.tsx
  src/app/my-page/reviews/page.tsx
  src/assets/mocks/myReviewList.ts
  src/components/common/StarRating.tsx
  src/components/my-page/SideMenu.tsx
  src/components/my-page/like/LikeItemCard.tsx
  src/components/my-page/like/LikeList.tsx
  src/components/my-page/modals/PasswordChangeModal.tsx
  src/components/my-page/modals/PhoneChangeModal.tsx
  src/components/my-page/modals/WithdrawalModal.tsx
  src/components/my-page/profile/ProfileDetail.tsx
  src/components/my-page/profile/ProfileInfoSection.tsx
  src/components/my-page/profile/WithdrawalButton.tsx
  src/components/my-page/review/ReviewDetailModal.tsx
  src/components/my-page/review/ReviewDetailView.tsx
  src/components/my-page/review/ReviewEditForm.tsx
  src/components/my-page/review/ReviewItemCard.tsx
  src/components/my-page/review/ReviewList.tsx
  src/components/word-cloud/WordCloud.tsx
  src/hooks/useMediaQuery.ts
  src/types/user/review.ts
Labels: ✨feature

#69 feat: 게임상세페이지 UI 구현(#28)
  package-lock.json
  package.json
  src/app/games/[id]/page.tsx
  src/app/globals.css
  src/app/my-page/reviews/page.tsx
  src/assets/mocks/gameListData.ts
  src/assets/mocks/myReviewList.ts
  src/components/game/GameTag.tsx
  src/components/game/GameTags.tsx
  src/components/game/LikeButton.tsx
  src/components/game/ShareButton.tsx
  src/components/game/detail/GameDetailInfo.tsx
  src/components/game/detail/GameReviewSection.tsx
  src/components/game/detail/GameThumbnailSection.tsx
  src/components/game/detail/ReviewList.tsx
  src/components/game/detail/ReviewModal.tsx
  src/components/game/detail/SimilarGameItem.tsx
  src/components/game/detail/SimilarGameList.tsx
  src/components/game/detail/YoutubeVideoSection.tsx
  src/components/my-page/review/MyReviewItemCard.tsx
  src/components/my-page/review/ReviewDetailModal.tsx
  src/components/my-page/review/ReviewDetailView.tsx
  src/components/my-page/review/ReviewEditForm.tsx
  src/components/my-page/review/ReviewList.tsx
  src/types/user/review.ts
  src/utils/formatDate.ts
Labels: ✨feature

#70 feat: 랭킹 페이지 UI 구현 (#56)
  src/app/ranking/page.tsx
  src/assets/mocks/gameRankingData.ts
  src/components/my-page/review/ReviewEditForm.tsx
  src/components/ranking/RankingItem.tsx
  src/components/ranking/RankingList.tsx
  src/components/ranking/RankingPageContent.tsx
  src/components/ranking/RankingTab.tsx
  src/constants/category/breadcrumbs.ts
  src/constants/category/menuItems.tsx
  src/types/game/gameRanking.ts
Labels: ✨feature

#75 feat: 보드Pick 설문 페이지 UI 구현 (#54)
  src/app/today/page.tsx
  src/app/today/result/page.tsx
  src/components/board-pick/IntroSection.tsx
  src/components/board-pick/QuestionCard.tsx
  src/components/board-pick/SurveyNav.tsx
  src/components/board-pick/SurveySection.tsx
  src/components/common/ProgressBar.tsx
  src/hooks/useBoardPickSurvey.ts
  src/types/board-pick/boardPick.ts
  src/utils/boardPick.ts
Labels: ✨feature

#65 feat: 회원가입페이지 ui 구현 (#26)
  src/app/auth/signup/page.tsx
  src/components/auth/EmailVerification.tsx
  src/components/auth/PhoneVerification.tsx
  src/components/auth/SignUpForm.tsx
  src/constants/form.ts
  src/hooks/auth/useSignUpForm.ts
  src/hooks/useBirthValidation.ts
  src/hooks/usePasswordValidation.ts
  src/types/auth/signup.ts
Labels: ✨feature

#77 feat: searchoverlay (#19)
  src/app/auth/signup/page.tsx
  src/components/auth/SignUpForm.tsx
  src/components/common/SearchOverlay.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/MobileSearchIcon.tsx
  src/components/layout/Header/SearchInput.tsx
  src/hooks/useDebounce.ts
  src/hooks/useSearch.ts
Labels: ✨feature

#71 feat: preference 페이지 (#53)
  public/images/splender.png
  src/app/preference/page.tsx
  src/components/survey/SurveyGameCard.tsx
Labels: ✨feature

#83 feat: React Query 전역 상태 관리 및 공통 fetcher 유틸 추가 (#78)
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/providers.tsx
  src/constants/api/queryClientOptions.ts
  src/lib/fetcher.ts
Labels: ✨feature

#86 feat: 로그인 api 연결 및 서버페이지로 변경
  src/actions/auth.ts
  src/app/auth/login/LoginForm.tsx
  src/app/auth/login/page.tsx
Labels: ✨feature

#90 feat: 회원가입 페이지 api연동 및 서버액션 구현 (#87)
  src/actions/auth.ts
  src/app/auth/signup/SignUpForm.tsx
  src/app/auth/signup/page.tsx
  src/components/auth/PhoneVerification.tsx
  src/hooks/auth/useSignUpForm.ts
  src/lib/fetcher.ts
  src/types/auth/signup.ts
Labels: ✨feature

#94 feat: 컴포넌트 세부 수정(#74)
  src/app/globals.css
  src/app/today/page.tsx
  src/components/board-pick/IntroSection.tsx
  src/components/common/Checkbox.tsx
  src/components/common/Radio.tsx
  src/components/common/RangeSlider.tsx
  src/components/game/FilterSidebar.tsx
  src/components/main/MainBannerCarousel.tsx
  src/components/main/NewAndHotGameSection.tsx
  src/components/main/RankItem.tsx
  src/components/main/RecommendedGameList.tsx
  src/components/main/RecommendedGameListSkeleton.tsx
  src/components/main/TrendingReviewCarousel.tsx
Labels: ♻️ refactor

#100 feat: 게임리스트 필터 개선(플레이시간 최소/최대 선택) (#99)
  next.config.ts
  src/components/common/DualRangeSlider.tsx
  src/components/game/FilterSidebar.tsx
Labels: ✨feature

#113 fix: 게임리스트 페이지 무한스크롤 수정 (#112)
  src/app/games/_components/GameListSection.tsx
  src/hooks/games/useGameFilters.ts
  src/hooks/useInfiniteGames.ts
Labels: 🐛 fix

#121 feat: 메인페이지 api 연동 및 mock 데이터 제거
  src/app/api/recommended-games/route.ts
  src/app/api/user/route.ts
  src/components/main/GameThemeCuration.tsx
  src/components/main/MainBannerCarousel.tsx
  src/components/main/NewAndHotGameSection.tsx
  src/components/main/PreferenceSurveyCTA.tsx
  src/components/main/RankItem.tsx
  src/components/main/RecommendedGameSection.tsx
  src/components/main/TrendingReviewSection.tsx
Labels: ✨feature

#132 feat: 게임 상세/리스트 SSR-CSR 통합 및 좋아요·유튜브 연동 기능 구현 (#114)
  src/app/api/games/[gameId]/route.ts
  src/app/api/games/route.ts
  src/app/api/likes/route.ts
  src/app/api/youtube/route.ts
  src/app/games/[id]/_components/GameDetailBottomSection.tsx
  src/app/games/[id]/_components/GameDetailPageHeader.tsx
  src/app/games/[id]/_components/GameDetailUI.tsx
  src/app/games/[id]/_components/YoutubeVideoSection.tsx
  src/app/games/[id]/page.tsx
  src/app/games/_components/GameListUI.tsx
  src/app/games/page.tsx
  src/components/game/LikeButton.tsx
  src/hooks/react-query/useToggleLike.ts
  src/lib/api/gameDetail.ts
  src/lib/api/games.ts
  src/lib/api/like.ts
  src/lib/api/reviews.ts
  src/lib/fetcher.ts
  src/lib/getQueryClient.ts
  src/types/api.ts
Labels: ✨feature

#130 docs: README.md 작성
  README.md
Labels: 📑 docs
